/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'AaronLong' at '8/21/16 8:28 PM' with Gradle 2.14.1
 *
 * @author AaronLong, @date 8/21/16 8:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
